name: ai-pill-mac
channels:
  - defaults
  - conda-forge
dependencies:
  - _anaconda_depends==2025.03
  - aext-assistant==4.1.0
  - aext-assistant-server==4.1.0
  - aext-core==4.1.0
  - aext-core-server==4.1.0
  - aext-panels==4.1.0
  - aext-panels-server==4.1.0
  - aext-project-filebrowser-server==4.1.0
  - aext-share-notebook==4.1.0
  - aext-share-notebook-server==4.1.0
  - aext-shared==4.1.0
  - aiobotocore==2.19.0
  - aiohappyeyeballs==2.4.4
  - aiohttp==3.11.10
  - aioitertools==0.7.1
  - aiosignal==1.2.0
  - alabaster==0.7.16
  - alembic==1.13.3
  - altair==5.0.1
  - anaconda-anon-usage==0.6.1
  - anaconda-auth==0.8.4
  - anaconda-catalogs==0.2.0
  - anaconda-cli-base==0.5.2
  - anaconda-client==1.13.0
  - anaconda-cloud-auth==0.8.4
  - anaconda-navigator==2.6.6
  - anaconda-project==0.11.1
  - anaconda-toolbox==4.1.0
  - anaconda_powershell_prompt==1.1.0
  - anaconda_prompt==1.1.0
  - annotated-types==0.6.0
  - anyio==4.6.2
  - aom==3.6.0
  - appdirs==1.4.4
  - archspec==0.2.3
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - arrow==1.3.0
  - arrow-cpp==19.0.0
  - astroid==3.3.8
  - astropy==7.0.0
  - astropy-iers-data==0.2025.1.13.0.34.51
  - asttokens==2.0.5
  - async-lru==2.0.4
  - asyncssh==2.17.0
  - atomicwrites==1.4.0
  - attrs==24.3.0
  - automat==20.2.0
  - autopep8==2.0.4
  - aws-c-auth==0.6.19
  - aws-c-cal==0.5.20
  - aws-c-common==0.8.5
  - aws-c-compression==0.2.16
  - aws-c-event-stream==0.2.15
  - aws-c-http==0.6.25
  - aws-c-io==0.13.10
  - aws-c-mqtt==0.7.13
  - aws-c-s3==0.1.51
  - aws-c-sdkutils==0.1.6
  - aws-checksums==0.1.13
  - aws-crt-cpp==0.18.16
  - aws-sdk-cpp==1.11.212
  - babel==2.16.0
  - bcrypt==3.2.0
  - beautifulsoup4==4.12.3
  - binaryornot==0.4.4
  - black==24.10.0
  - blas==1.0
  - bleach==6.2.0
  - blinker==1.9.0
  - blosc==1.21.3
  - bokeh==3.6.2
  - boltons==24.1.0
  - boost-cpp==1.82.0
  - botocore==1.36.3
  - bottleneck==1.4.2
  - brotli==1.0.9
  - brotli-bin==1.0.9
  - brotli-python==1.0.9
  - bzip2==1.0.8
  - c-ares==1.19.1
  - c-blosc2==2.12.0
  - ca-certificates==2025.2.25
  - cachetools==5.5.1
  - certifi==2025.4.26
  - cffi==1.17.1
  - cfitsio==3.470
  - chardet==4.0.0
  - charls==2.2.0
  - charset-normalizer==3.3.2
  - click==8.1.7
  - cloudpickle==3.0.0
  - colorama==0.4.6
  - colorcet==3.1.0
  - comm==0.2.1
  - conda==25.3.1
  - conda-build==25.1.2
  - conda-content-trust==0.2.0
  - conda-index==0.5.0
  - conda-libmamba-solver==25.1.1
  - conda-pack==0.7.1
  - conda-package-handling==2.4.0
  - conda-package-streaming==0.11.0
  - conda-repo-cli==1.0.165
  - conda-token==0.6.0
  - constantly==23.10.4
  - contourpy==1.3.1
  - cookiecutter==2.6.0
  - cpp-expected==1.1.0
  - cryptography==44.0.1
  - cssselect==1.2.0
  - curl==8.12.1
  - cycler==0.11.0
  - cytoolz==1.0.1
  - dask==2024.12.1
  - dask-core==2024.12.1
  - dask-expr==1.1.21
  - datashader==0.17.0
  - dav1d==1.2.1
  - debugpy==1.8.11
  - decorator==5.1.1
